#!/bin/bash

sudo apt-get update
apt-get --yes update && apt-get --yes upgrade && apt-get --yes dist-upgrade

#set the ubuntu environment variables DEBIAN_FRONTEND TO noninteractive
export DEBIAN_FRONTEND=noninteractive

sudo apt-get -y install libnss-ldap libpam-ldap ldap-utils nscd nslcd debconf-utils

unset DEBIAN_FRONTEND

#echo "cloning fjemal01's NTI-310 GitHub..."
git clone https://github.com/fjemal/NTI-310.git /tmp/NTI-310
git config --global user.name "fjemal"
git config --global user.email "fjemal01@seattlecentral.edu"

cp /tmp/NTI-310/config_scripts/ldap.conf /etc/ldap.conf

#configure ldap client

#use sed to add config lines to /etc/ldap.conf
sed -i 's,#BASE   dc=example\,dc=com,BASE	dc=ldap\,dc=local,g' /etc/ldap/ldap.conf
sed -i 's,##URI	ldap:\/\/ldap.example.com ldap:\/\/ldap-master.example.com:666,URI	ldaps:\/\/10.128.0.4'

sed -i 's,uri ldapi:///,uri ldap://10.128.0.0/,g' /etc/ldap/ldap.conf
sed -i -e "s/pam_password md5/pam_password ssha/" /etc/ldap/ldap.conf
sed -i 's,#rootbinddn cn=manager\,dc=example\,dc=net,rootbinddn cn=manager\,dc=example\,dc=net,g' /etc/ldap/ldap.conf
#ldap://Server-IP-address #change lpdapi:/// to ldap:// 
#use ldap version 3
# dc=ldap,dc=local
#cn=ldapadm,dc=ldap,dc=local

#Configure authentication:
# /etc/nsswitch.conf
# vi /etc/nsswitch.conf  >>>>>>>>>>user stream edetor "sed"

sed -i 's,passwd:         compat,passwd:         ldap compat,g' /etc/nsswitch.conf
sed -i 's,group:          compat,group:          ldap compat,g' /etc/nsswitch.conf
sed -i 's,shadow:         compat,shadow:         ldap compat,g' /etc/nsswitch.conf
#passwd:         ldap compat
#group:          ldap compat
#shadow:         ldap compat



#hosts:          files resolve [!UNAVAIL=return] dns
#networks:       files

#protocols:      db files
#services:       db files

#ethers:         db files
#rpc:            db files

#netgroup:       nis

#edit pam.d 
#vi /etc/pam.d/common-session

#add following line at the bottom: 
sed -i '$ a\session required    pam_mkhomedir.so skel=/etc/skel umask=0077' /etc/pam.d/common-session
#restart the service
/etc/init.d/nscd restart

sed -i 's/%admin=(ALL) ALL/#%admin ALL=(ALL) ALL/g' /etc/sudoers                                        #  <<<<<<<<<comment out

cd /etc/ssh
#if permission denied cp sshd_config sshd_config.bak
#vi sshd_config

#comment out 
sed -i 's/PasswordAuthentication no/#PasswordAuthentication no/g' /etc/ssh/sshd_config
#comment out 
sed -i 's/ChallengeResponseAuthentication no/#ChallengeResponseAuthentication no/g' /etc/ssh/sshd_config

#restart the sshd service
systemctl restart sshd.service 




