#!/bin/bash
echo "installing git"
yum -y install git
echo "clonig git"
echo "cloning fjemal's NTI-310 GitHub..."
git clone https://github.com/fjemal/NTI-310.git /tmp/NTI-310
git config --global user.name "fjemal"
git config --global user.email "fjemal01@seattlecentral.edu"
#Installing ldap server
#https://www.server-world.info/en/note?os=CentOS_7&p=openldap

#This is a basis for students to create a fully functioning build, compile, and deploy script.
echo "intalling servers and clients packages"
yum -y update
yum -y install openldap compat-openldap openldap-clients openldap-servers openldap-servers-sql openldap-devel
cp /usr/share/openldap-servers/DB_CONFIG.example /var/lib/ldap/DB_CONFIG 
chown ldap /var/lib/ldap/DB_CONFIG
sleep 5

# Tell SE linux what's going on, so that it doesn't freek
echo "starting enabling and starting apache"

systemctl enable slapd
systemctl start slapd

yum -y install httpd
yum -y install epel-release
yum -y install phpldapadmin

echo "installing and enabling apache server"
yum -y install httpd
systemctl enable httpd
systemctl start httpd

setsebool -P httpd_can_connect_ldap on
sed -i 's,Require local,#Require local\n    Require all granted,g' /etc/httpd/conf.d/phpldapadmin.conf
# decent config guide: http://www.itzgeek.com/how-tos/linux/centos-how-tos/install-configure-phpldapadmin-centos-7-ubuntu-16-04.html
#Note: LDAP comes up completely insecure, with Anonymous login enabled by default... this is not a good and happy thing, so fix 
#it in the config file
#(prompt for user input), the following is currently a manual config, but could be automated fairly easily
 
echo "phpldapadmin is now up and running"
echo "configuring ldap and ldapamdin"

#echo "generating ldap slappasswrd"

newsecret=$(slappasswd -g)
newhash=$(slappasswd -s "$newsecret")
echo -n "$newsecret" > /root/ldap_admin_pass
chmod 600 /root/ldap_admin_pass
sleep 5

 echo "dn: olcDatabase={2}hdb,cn=config
changetype: modify
replace: olcSuffix
olcSuffix: dc=ldap,dc=local

dn: olcDatabase={2}hdb,cn=config
changetype: modify
replace: olcRootDN
olcRootDN: cn=ldapadm,dc=ldap,dc=local

dn: olcDatabase={2}hdb,cn=config
changetype: modify
replace: olcRootPW
olcRootPW: $newhash" >> db.ldif

#echo "add db.ldif to ldap configuration"
ldapmodify -Y EXTERNAL  -H ldapi:/// -f db.ldif

#restrict monitor users
#cat <<EOT>> /etc/openldap/slapd.d/monitor.ldif
echo 'dn: olcDatabase={1}monitor,cn=config
changetype: modify
replace: olcAccess
olcAccess: {0}to * by dn.base="gidNumber=0+uidNumber=0,cn=peercred,cn=external, cn=auth" read by dn.base="cn=ldapadm,dc=ldap,dc=local" read by * none' > monitor.ldif

#EOT
ldapmodify -Y EXTERNAL  -H ldapi:/// -f monitor.ldif

openssl req -new -x509 -nodes -out /etc/openldap/certs/fjldapcert.pem -keyout /etc/openldap/certs/fjldapkey.pem -days 365 -subj "/C=US/ST=WA/L=Seattle/O=IT/OU=NTI310/CN=ldap.local"
chown -R ldap /etc/openldap/certs/fj*.pem
#chown -R ldap. /etc/openldap/certs/fjldapkey.pem
#cp /tmp/NTI-310/config_scripts/certs.ldif /etc/openldap/slapd.d/certs.ldif
#ldapmodify -Y EXTERNAL  -H ldapi:/// -f /etc/openldap/slapd.d/certs.ldif
# Test cert configuration

echo "dn: cn=config
changetype: modify
replace: olcTLSCertificateFile
olcTLSCertificateFile: /etc/openldap/certs/fjldapcert.pem

dn: cn=config
changetype: modify
replace: olcTLSCertificateKeyFile
olcTLSCertificateKeyFile: /etc/openldap/certs/fjldapkey.pem" > certs.ldif

ldapmodify -Y EXTERNAL -H ldapi:/// -f certs.ldif

slaptest -u

cp /usr/share/openldap-servers/DB_CONFIG.example /var/lib/ldap/DB_CONFIG 
chown ldap:ldap /var/lib/ldap/*

#Set up LDAP database
echo "Adding schemas"
ldapadd -Y EXTERNAL -H ldapi:/// -f /etc/openldap/schema/cosine.ldif
ldapadd -Y EXTERNAL -H ldapi:/// -f /etc/openldap/schema/nis.ldif
ldapadd -Y EXTERNAL -H ldapi:/// -f /etc/openldap/schema/inetorgperson.ldif

#echo "adding new entry cn=inetorgperson,cn=schema,cn=config"
echo "generating base.ldif file for your domain"

#chown ldap: /etc/openldap/slapd.d/base.ldif
#echo "Creating base.ldif"
echo "dn: dc=ldap,dc=local
dc: ldap
objectClass: top
objectClass: domain

dn: cn=ldapadm ,dc=ldap,dc=local
objectClass: organizationalRole
cn: ldapadm
description: LDAP Manager

dn: ou=People,dc=ldap,dc=local
objectClass: organizationalUnit
ou: People

dn: ou=Group,dc=ldap,dc=local
objectClass: organizationalUnit
ou: Group" > base.ldif 

ldapadd -x -W -D "cn=ldapadm,dc=ldap,dc=local" -f base.ldif -y /root/ldap_admin_pass
#ldapadd -x -D "cn=ldapadm,dc=ldap,dc=local" -f base.ldif -y /root/ldap_admin_pass

#allow firewall

sleep 5

echo "creating selfsigned key"
openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/ssl/private/apache-selfsigned.key -subj "/C=US/ST=WA/L=Seattle/O=IT/OU=NTI310/CN=ldap.local" -out /etc/ssl/certs/apache-selfsigned.crt
openssl dhparam -out /etc/ssl/certs/dhparam.pem 2048
cat /etc/ssl/certs/dhparam.pem | tee -a /etc/ssl/certs/apache-selfsigned.crt
#modify /etc/httpd/conf.d/ssl.conf
sleep 5
cp /tmp/NTI-310/config_scripts/config.php /etc/phpldapadmin/config.php  
sed -i -e "s/\/\/ \$servers->setValue('login','anon_bind',true);/\$servers->setValue('login','anon_bind',false);/" /etc/phpldapadmin/config.php

sed -i 's/SLAPD_URLS="ldapi:\/\/\/ ldap:\/\/\/"/SLAPD_URLS=\"ldapi:\/\/\/ ldap:\/\/\/ ldaps:\/\/\/"/g' /etc/sysconfig/slapd
sed -i 's,Require local,#Require local\n    Require all granted,g' /etc/httpd/conf.d/phpldapadmin.conf
systemctl restart httpd
systemctl restart slapd
#allow firewall
echo "configuring the firewall"
firewall-cmd --permanent --add-port=636/tcp
firewall-cmd --permanent --zone=public --add-service=http
firewall-cmd --reload
