#!/bin/bash

#install and config nfs client
apt-get -y install nfs-client nfs-common nfs-kernel-server
#apt-get -y install nfs-common
service nfs-kernel-server start

echo "making dir for nfs"
mkdir -p /mnt/nfs/home
mkdir -p /mnt/nfs/var/dev
mkdir -p /mnt/nfs/var/config
#Start the services and add them to boot menu
systemctl enable rpcbind
systemctl enable nfs-server
systemctl enable nfs-lock
systemctl enable nfs-idmap
systemctl start rpcbind
systemctl start nfs-server
systemctl start nfs-lock
systemctl start nfs-idmap
mount -t nfs  "10.128.0.3":/home /mnt/nfs/home
mount -t nfs  "10.128.0.3":/var/dev /mnt/nfs/var/dev
mount -t nfs  "10.128.0.3":/var/nfsshare /mnt/nfs/var/config
#check if connected  with nfs share

echo "10.128.0.3:/home            /mnt/nfs/home           nfs     defaults 0 0" >> /etc/fstab
echo "10.128.0.3:/var/dev         /mnt/nfs/var/dev        nfs     defaults 0 0" >> /etc/fstab
echo "10.128.0.3:/var/config      /mnt/nfs/var/config     nfs     defaults 0 0" >> /etc/fstab


apt-get -y install tree
mount -a
df -h
 tree /mount
