#!/bin/bash
echo "installing git"
yum -y install git
#echo "cloning fjemal01's NTI-310 GitHub..."
git clone https://github.com/fjemal/NTI-310.git /tmp/NTI-310
git config --global user.name "fjemal"
git config --global user.email "fjemal01@seattlecentral.edu"
echo "updating the server"

sudo yum -y update

echo "installing postgres"
sudo yum install postgresql-server postgresql-contrib
sudo yum install epel-release
sudo postgresql-setup initdb
systemctl start postgresql.service
#Edit /var/lib/pgsql/data/postgresql.conf and configure PostgreSQL to listen on localhost:
#sudo vim /var/lib/pgsql/data/postgresql.conf
#Set the following parameter:

systemctl start postgresql.service
sudo yum -y install httpd
sudo systemctl enable httpd
sudo systemctl start httpd
sudo cp /tmp/NTI-310/config_scripts/postgres.sql /var/lib/pgsql/postgres.sql
#sudo -i -u postgres psql -U postgres -f /var/lib/pgsql/postgres.sql

#listen_addresses = 'localhost'
sudo sed -i "s/#listen_addresses = 'localhost'/listen_addresses = '*'/g" /var/lib/pgsql/data/postgresql.conf

#or execute the following command
#sudo sed -i 's/^#listen_addresses /listen_addresses/' /var/lib/pgsql/data/postgresql.conf
sudo sed -i 's/\(host  all  all   10.128.0.0\/9  *\)ident/\1md5/' /var/lib/pgsql/data/pg_hba.conf
sudo sed -i 's/\(host  all  all  10.128.0.0\/9  \)ident/\1md5/' /var/lib/pgsql/data/pg_hba.conf
sudo sed -i "s/ident/md5/g" /var/lib/pgsql/data/pg_hba.conf
sudo sed -i -e "\$ahost    all             all             0.0.0.0/0      md5" /var/lib/pgsql/data/pg_hba.conf
sudo -i -u postgres pg_ctl reload
sudo systemctl restart postgresql.service
sudo systemctl start postgresql
sudo systemctl enable postgresql

#sudo -i -u postgres
# log into postgres account
#You can get a Postgres prompt immediately by typing:
#psql
#Exit out of the PostgreSQL prompt
#\q
sudo yum -y install phpPgAdmin
sed -i 's,  Require local,  Require all granted,g' /etc/httpd/conf.d/phpPgAdmin.conf
sudo cp /tmp/NTI-310/config_scripts/config.inc.php /etc/phpPgAdmin/config.inc.php
#echo "CREATE DATABASE postgres ;
#ALTER USER postgres WITH PASSWORD 'P@ssw0rd1';
#CREATE DATABASE project1;
#CREATE USER project1 WITH PASSWORD 'P@ssw0rd1';
#ALTER ROLE project1 SET client_encoding TO 'utf8';
#ALTER ROLE project1 SET default_transaction_isolation TO 'read committed';
#ALTER ROLE project1 SET timezone TO 'UTC';
#GRANT ALL PRIVILEGES ON DATABASE project1 TO project1;
#\q " > /tmp/NTI-310/config_scripts/postgres.sql
sudo -i -u postgres psql -U postgres -f /var/lib/pgsql/postgres.sql
sudo setsebool -P httpd_can_network_connect_db on
sudo systemctl restart postgresql
sudo systemctl restart httpd
sudo firewall-cmd --permanent --zone=public --add-service=postgresql
firewall-cmd --permanent --add-port=5432/tcp
firewall-cmd --permanent --add-port=80/tcp
firewall-cmd --reload
sudo firewall-cmd --reload
