#!/bin/bash
echo "installing git"
yum -y install git
#echo "cloning fjemal01's NTI-310 GitHub..."
git clone https://github.com/fjemal/NTI-310.git /tmp/NTI-310
git config --global user.name "fjemal"
git config --global user.email "fjemal01@seattlecentral.edu"
echo "Current python version:"
echo "updating the server"
sudo yum -y update
echo "installing postgres"
sudo yum install postgresql-server postgresql-contrib
sudo yum install epel-release
sudo postgresql-setup initdb
systemctl start postgresql.service
#Edit /var/lib/pgsql/data/postgresql.conf and configure PostgreSQL to listen on localhost:
#sudo vim /var/lib/pgsql/data/postgresql.conf
#Set the following parameter:
sudo cp /tmp/NTI-310/config_scripts/postgressql.conf /var/lib/pgsql/postgressq.conf
sudo -i -u postgres psql -U postgres -f /var/lib/pgsql/postgressql.conf
#listen_addresses = 'localhost'

#or execute the following command
sudo sed -i 's/^#listen_addresses /listen_addresses/' /var/lib/pgsql/data/postgresql.conf
sudo sed -i 's/\(host  all  all   10.128.0.0\/9  *\)ident/\1md5/' /var/lib/pgsql/data/pg_hba.conf
sudo sed -i 's/\(host  all  all  10.128.0.0\/9  \)ident/\1md5/' /var/lib/pgsql/data/pg_hba.conf
sudo -i -u postgres pg_ctl reload
sudo systemctl restart postgresql.service
sudo systemctl start postgresql
sudo systemctl enable postgresql
sudo firewall-cmd --permanent --zone=public --add-service=postgresql
sudo firewall-cmd --reload

#sudo -i -u postgres
# log into postgres account
#You can get a Postgres prompt immediately by typing:
#psql
#Exit out of the PostgreSQL prompt
#\q
sudo yum -y install phpPgAdmin
sed -i 's,  Require local,  Require all granted,g' /etc/httpd/conf.d/phpPgAdmin.conf
sudo cp /tmp/NTI-310/config_scripts/config.inc.php /etc/phpPgAdmin/config.inc.php

sudo setsebool -P httpd_can_network_connect_db on
sudo systemctl restart postgresql
sudo systemctl restart httpd
